(function(z){
'use strict';var k$=function(a){z.L.call(this);this.w(a)},K3a=function(a,b){this.user=a;this.quotes=b},L3a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},l$=function(a){return a.iA.best||null},m$=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.gb(b,function(a){return a.mb()},a);return z.lb(b).map(function(a){return new K3a(a[0].pc(),a)},a)},M3a=function(a,b,c,d){return(0,z.pd)(a.kt[b.name]||
[],function(a){return a.Bd()==c&&a.ze()==d})},n$=function(){this.yF=1},o$=function(a){z.jk.call(this);this.w(a)},N3a=function(a,b){return z.K(a,"slots",b)},O3a=function(a,b){return z.K(a,"requestContext",b)},p$=function(a){z.L.call(this);this.w(a)},q$=function(a){return z.J(a,"inResponseToMediaResource")},r$=function(a){return z.J(a,"mediumQuote")},P3a=function(a,b){a.qO=b;return a},s$=function(a,b){return l$(a)?z.XE(l$(a)).filter(function(a){return this.f3(a)==b},a):[]},Q3a=function(a,b,c){c=c.mx;
b=b.getAttribute("name").split(" ");var d=z.xb(b);a=(a.kt[c.name]||[]).filter(function(a){return d[a.Si()]});return a.length?z.Lra(a):null},R3a=function(a,b,c,d){b=M3a(a,b,c,d);return m$(a,b)},S3a=function(a,b){var c=0;(a.kt[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Oe())});return c},T3a=function(a){var b=z.CP(a.Tj.Ks,a.Tj.Yq(),a.Wl.Ks,a.Wl.Yq()).Ga().trim();0<a.Tj.Yq()&&(b="…"+b);var c=z.hH(a.yc,a.Wl.Ks);a.Wl.Yq()<c.Ga().length&&(b+="…");return b},U3a=function(a){var b=z.WD(a.Uva),c=a.Tj.Ks,
d=c?b.indexOf(c):-1,e=(c=a.Wl.Ks)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.hH(a.yc,b[d]));b=z.Qa(c);a=z.Hx(c.indexOf(c[0]),a.Tj.Yq(),c.indexOf(b),a.Wl.Yq(),!1);return z.Fha(new z.tx(z.Cr,z.yxa),c,a,!0)},V3a=function(a,b,c){var d=a.la.ka(z.cza,{postId:b},{filter:c});return z.UG(a,d,function(){return this.Ab.zj(d)})},W3a=function(a,b){z.bx(a,7);var c=new z.Tw("",1,a.Ga());b.forEach(function(a){z.$w(c,z.Lw(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.sha(c);for(var d=
z.tha(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],q=0;q<g.length;q++){var r=g[q];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];q=e<b.length-1?b[e+1]:a.Ga().length;z.$w(a,z.Lw(g,q,l,Object.keys(k)))}}},X3a=function(a,b,c){b="";a.IDa?a=z.n("Top highlight"):(c=""+z.A(z.DR(z.D({l4:!0,bja:!c.useragent.isMobile},a),c)),1==a.zi&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},t$=function(a,b){this.ji=a;this.Ipa=b;this.Le=(this.Ek=b=z.RD(a.node,
b))&&b.getAttribute("name");this.eO=b?z.wA(a,b):-1},Y3a=function(a,b,c){return(0,z.y)(z.dR(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},Z3a=function(a,b,c){b='\x3cdiv\x3e\x3cdiv class\x3d"buttonSet u-inlineBlock"\x3e'+z.A(z.Jn({action:"quote",source:"quote_popover",icon:(0,z.O)(""+z.A(z.lp())),l:(0,z.O)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),Yb:!0,Ai:!0,bea:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?
z.A(z.Jn({action:"quote-respond",source:"quote_popover",icon:(0,z.O)(""+z.A(z.zp())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",Yb:!0,wa:!0},c)):"")+(a.cU?z.A(z.Jn({action:"twitter",source:"quote_popover",icon:(0,z.O)(""+z.A(z.Dp())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",Yb:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop14 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+X3a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},u$=function(a){z.Dr.call(this);var b=z.Ds();this.Tj=b&&new t$(z.et(b,!0),a);this.Wl=b&&new t$(z.et(b,!1),a)},v$=function(a){z.L.call(this);this.w(a)},w$=function(a,b){var c=new z.al(z.Br(b)),c=new z.Td(c.ka(z.Zxa)),d=new z.Td("https://www.facebook.com/v2.7/dialog/share");z.Xd(d,z.ne({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},$3a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},
a4a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.A5&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({s6:b},a),d=d||{},d=d.s6;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+
z.A(z.rq({title:(0,z.O)(""+z.A(z.eo())),XB:!0,Df:(0,z.O)(""+(c.supportsEdit&&d?z.xMa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.vMa(z.D({Qe:b},a),c)+(b?z.wMa(a,c):"")+z.uMa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},b4a=function(a,b,c){b=z.y;var d="",e=z.n("Explore your homepage for more \x26rarr;"),g=z.n("Here are some handpicked stories for you."),k=z.n("Welcome"),l;l=l={user:c.currentUser};var q="u-size88x88 u-xs-size80x80"+(l.II?" "+l.II:""),q=z.E(q);l=""+z.aq(z.D({width:88,height:88,
Ah:q},l),c);l=(0,z.y)(l);d+='\x3cdiv class\x3d"u-flexCenter"\x3e\x3cdiv class\x3d"u-flex0 u-paddingRight20"\x3e'+z.A(l)+'\x3c/div\x3e\x3cdiv class\x3d"u-flex1"\x3e\x3cdiv class\x3d"u-contentSansBold u-fontSize22"\x3e'+k+", "+z.A(c.currentUser.name)+'!\x3c/div\x3e\x3cdiv class\x3d"u-contentSansBold u-fontSize22"\x3e'+g+"\x3c/div\x3e"+z.A(z.Q({href:(0,z.M)(""+z.G(z.ml(c))),s:(0,z.O)(""+e),ye:"homepage-link-clicked",rb:!1,l:"u-contentSansRegular u-fontSize14 u-lineHeightLoose"},c))+'\x3c/div\x3e\x3cdiv class\x3d"u-flex0 u-alignSelfStart"\x3e'+
z.A(z.Fn({s:(0,z.O)("\x26times;"),action:"toggle-drawer",wa:!0,l:"u-fontSize32 u-lineHeight0"},c))+"\x3c/div\x3e\x3c/div\x3e";e='\x3cdiv class\x3d"drawer u-heightAuto u-zIndex2 js-drawer"\x3e\x3cdiv class\x3d"u-maxWidth1000 u-marginAuto u-paddingTop40 u-paddingBottom60"\x3e'+(0,z.y)(d);g='\x3cdiv class\x3d"u-flex u-paddingTop40"\x3e';a=a.placements;k=a.length;for(d=0;d<k;d++)g+='\x3cdiv class\x3d"u-size4of12'+(0!=d%3?" u-marginLeft10":"")+(0!=(d+1)%3?" u-marginRight10":"")+' u-xs-size12of12"\x3e'+
z.A(z.QEa({placementCard:a[d],index:d,Mp:c.j.xc.yla},c))+"\x3c/div\x3e";c=(0,z.y)(g+"\x3c/div\x3e");return b(e+c+"\x3c/div\x3e\x3c/div\x3e")},c4a=function(a){return(0,z.y)(z.A(z.ao(String(a.content)))+" — "+z.A(z.uI(a))+" "+z.A(a.url))},d4a=function(a,b,c){return(0,z.Ik)("https://"+z.Oi(c.textshotHost)+"/image")},e4a=function(a,b,c){return(0,z.Ik)("https://twitter.com/"+z.Oi(c.currentUser.twitterScreenName)+"/status/"+z.Oi(a.id))},f4a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+
b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},g4a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+z.A(z.fq({user:a.user,Ze:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';
var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.zo(z.D({name:"addCircled",size:"21px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.O)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.Jn({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.O)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.O)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.Fn({s:d,Cc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.O)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},h4a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},i4a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.IHa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.Q({rb:!0,href:a,s:(0,z.O)(""+e)},c));return(0,z.y)(d)},j4a=function(){var a=z.n("Tweet must be 140 characters or less.");return(0,z.y)(""+a)},x$=function(a,b,c){z.R.call(this);this.ve=a.get("quotes-data");var d=this.ve.Lo;d.subscribe("add",this.jca,this);d.subscribe("remove",this.jca,this);this.eb=b;this.Pd=b.Tl;this.bm=c;this.J9=[];this.Ia=a.get("app");this.Da=a.get("popover");this.la=a.get("route-builder");this.cY=a.get("global-event-bus");this.gwa=a.get("progressive-media-loader")},
l4a=function(a,b,c,d){var e=k4a(a,b);if(e){var g=a.eb.isPublished(),k=z.esa(a.eb);e.cU=g&&k;if(c=z.sH(z.tF(z.sF(z.uF(z.rF(z.vF(a.Da).cb(Z3a,e),z.wF),c),{oS:!0,ou:!0,Ca:!0}),"popover--quoteAttributions"),d).qa())c.ao("deactivate",function(){this.Vo===b&&y$(this,null)},a),c.Fn().aa("quote",a.Hqa.bind(a,c)).aa("quote-respond",a.Iqa.bind(a,c)).aa("twitter",a.Jqa.bind(a))}},k4a=function(a,b){if("anon"==b.mb())return{isActive:!1,IDa:!0};var c=z$(a,b),d=b.Bd();b=b.ze();a=R3a(a.ve,c,d,b);if(!a||!a.length)return null;
a=(0,z.zb)(a,function(a){return a.user});c=(0,z.pd)(a,function(a){return a.userId!=z.Ou().userId});return{isActive:(0,z.Wc)(a,function(a){return a.userId==z.Ou().userId}),social:c,zi:a.length}},m4a=function(a,b){a=a.Pd.querySelectorAll('.markup--quote[name~\x3d"'+b.Si()+'"]');return z.Za(a)},z$=function(a,b){b=b.hc()[0].name;return(b=z.xw(a.Pd,b))?a.eb.Ri(b):null},n4a=function(a,b){var c=z.Es(b);return(c=z.dI(a.bm,c))?Q3a(a.ve,b,c):null},y$=function(a,b){a.Vo!==b&&(a.Vo&&o4a(a,a.Vo,!1),b&&o4a(a,b,
!0),a.Vo=b)},o4a=function(a,b,c){m4a(a,b).map(function(a){z.sd(a,"is-targeted",c)})},A$=function(a,b){(b=p4a(a,b))&&z.bI(a.fk(),b)},p4a=function(a,b){var c=b.hc(),d=z.xw(a.Pd,c[0].getName());a=z.xw(a.Pd,z.Qa(c).getName());return z.CP(d,b.Bd(),a,b.ze())},B$=function(a,b,c,d){a={postId:a.eb.La(),quoteId:b,source:d};z.yB(c?z.Sra:z.AAa,a)},q4a=function(a,b){z.VD(a,z.UD,z.Ob(b,z.Lb(!0)),void 0)},C$=function(a){z.jk.call(this);this.w(a)},r4a=function(a,b,c){z.qa(a)||(a=a.toString());var d=window,e={scrollbars:!0,
tGa:!0,toolbar:!1,location:!0,width:670,height:690};z.vb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",tGa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.Ofa(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":
"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();return d.open(a,b,c)},s4a=function(a){var b=z.Wz(z.pta,{AEa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Ea(a)}),b.length&&z.od(a,b))},t4a=function(a){if(!a)return"";var b=[],c=z.tb(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},D$=function(a){z.UA.call(this);this.yc=a.get("dom-model-converter");this.fba={};this.Y$={};this.k_={};this.ra=a;this.Yk=a.get("request");this.la=a.get("route-builder");
this.ya=a.get("model-store");this.kb="";this.Iba=z.tr;this.G9=!1;this.Fh=null},E$=function(a,b){var c=a.fba[b];c||(c=a.fba[b]=new z.SE,a.za("new_note_list",c,a));return c},u4a=function(a,b){if(!b)return!1;var c=b.Ga();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ha(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):!1},F$=function(a,b,c){var d=b.La(),e=b.Ag(),g=E$(a,b.ne()),
k=g?g.indexOf(b):-1,l=b.qI();b.fy(c);"HIDDEN"==c?a.ya.remove(b):b=z.OE(a.ya,b);var q=g?g.indexOf(b):-1;return{ll:a.Yk.put(a.la.ka(z.hya,{postId:d,noteId:e}),{state:c}),zJ:function(){b.fy(l);-1==q&&(-1==k?g.add(b):z.UE(g,b,k))}}},G$=function(a,b,c,d,e,g){var k=z.J(a.pp(c,e),"replies"),l=z.Sa(k,function(a){return a.fx()==b}),q=k[l];"HIDDEN"==g&&z.Wa(k,l);c=a.la.ka(z.kya,{postId:d,noteId:c,replyId:b});a=a.Yk.put(c,{state:g});var r=z.Sa(k,function(a){return a.fx()==b});return{ll:a,zJ:function(){-1==r&&
z.bb(k,l,0,q)}}},v4a=function(a,b,c){this.range=a;this.anchor=b;this.HA=b.getAttribute("name");this.highlight=c},H$=function(a,b,c){z.R.call(this);this.WO=b;this.Rva=c;this.Ma=a.get("screen");this.fb=a.get("screen-request")},w4a=function(a,b){b=b.querySelectorAll(".js-trackedPostPromotion");null!=a.WO.postPageContext&&null!=a.WO.postPageContext.postId&&z.Za(b).forEach(function(b){var d=a.WO.postPageContext.postId,e=b.getAttribute("data-post-id"),g=b.getAttribute("data-post-promotion-source");b=b.getAttribute("data-location-id");
z.yB(z.dBa,{hostPostId:d,targetPostId:e,promotionSource:g,locationId:b})})},x4a=function(){},y4a=function(a){this.dO=a},I$=function(a,b){return b?z.xw(a.dO,b):null},z4a=function(a,b,c){q4a(a.dO,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})},A4a=function(a,b){return z.xh(a.dO,b)?a.dO:null},J$=function(a,b,c,d,e){z.eY.call(this,a,b);this.bb(new z.wX(c));this.bb(new z.NY(!1));this.bb(new z.PY(a));this.bb(new z.fY);this.bb(new z.xZ(a,!1,!1));this.bb(new z.RZ(d,!0));this.Vk=!0;this.am=d;
this.Yk=a.get("request");this.Ea=a.get("dialog");this.OZ=e;this.qa()},B4a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+a)},C4a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},D4a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},E4a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");
return(0,z.y)(""+a)},F4a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},G4a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},H4a=function(){var a=z.n("The reply has been deleted.");return(0,z.y)(""+a)},I4a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},J4a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},K$=function(a,b,c,d,e){J$.call(this,a,b,e||"Leave a note",400,d||null);this.kb=c;this.la=a.get("route-builder");this.tf=a.get("notes-data")},
L$=function(a,b,c,d,e,g){J$.call(this,a,b,"Leave a reply…",200,d);this.la=a.get("route-builder");this.tf=a.get("notes-data");this.kb=c;this.fca=g||null;this.Le=e},L4a=function(a,b,c){var d='\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.T6;b=a.notes.length||a.$T;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.sq({title:(0,z.O)(z.A($3a())+" ("+z.A(a.quotes.length)+")"),wf:!0},c)),k;k={kia:a.quotes,fIa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';
if(!k.fIa)var q=z.n("Learn more"),l=l+z.A(z.sq({title:(0,z.O)(""+z.A($3a())),wf:!0,Df:(0,z.O)(""+z.A(z.qq({href:(0,z.M)(""+z.G((0,z.Ik)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:(0,z.O)(""+q),yb:!0},c)))},c));for(var q="list u-marginTop5 u-marginBottom15"+(k.kia.length?"":" u-hide"),q=(0,z.O)(q),l=l+('\x3cul class\x3d"'+z.F(q)+'"\x3e'),q=k.kia,r=q.length,u=0;u<r;u++){for(var v=q[u],C="",H=v.quotes,P=H.length,N=0;N<P;N++)C+=""+H[N].quoteId+(N!=P-1?",":"");C=z.E(C);
l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(C)+'" data-quote-creator-id\x3d"'+z.F(v.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+z.A(z.dq(z.D({user:v.user,Ee:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.T6?" is-withEditor":"")+'"\x3e'+z.A(z.sq({title:(0,z.O)(""+z.A(z.eo())),wf:!0},c)),a.T6&&c.supportsEdit&&c.isAuthenticated?
(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.dR(z.D({user:c.currentUser,isCollapsed:!0,VB:!0,type:"quoteResponses",Eu:(0,z.O)(""+z.A(z.mo()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+K4a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.HFa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=
c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.O)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+
'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.zo(z.D({name:"lock",size:"19px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.O)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={BHa:g,title:(0,z.O)(""+z.A(e)),wf:!0,Df:(0,z.O)(b),l:"heading--privateNotes"};b=(0,z.y)(z.oq(z.D({uj:(0,z.O)(""+z.pq(b,c)),uEa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.$T?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=M$({note:g[k],post:a.post,YJ:a.YJ},0,c);a.$T?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.Gn({action:"show-note-editor",text:(0,z.O)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.eq({user:c.currentUser,Ze:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.Gn({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.O)(""+z.A(k))},0,c))+z.A(z.Gn({action:"hide-note-editor",text:(0,z.O)(""+z.A(J4a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.KC&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.Jn({wb:!0,Cc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.O)(""+z.A(z.Fo())),title:(0,z.O)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.Jn({wb:!0,Cc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.O)(""+z.A(z.Io())),title:(0,z.O)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},K4a=function(a,b,c){return(0,z.y)(z.A(z.OR({posts:a.responses,source:"quoteResponses",
VR:!0},0,c)))},M$=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var q=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),q=z.E(q),q='\x3cdiv class\x3d"privateNotes-item '+
z.F(q)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.dq({user:a.note.author},c)):z.A(z.bq({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.Un({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.Jga?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");q=
q+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.qj(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.ky(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.Vh(k,z.Yh)?(0,z.y)(l,z.Wh(k)):l;d=""+(q+k+"\x3c/div\x3e"+(d?M4a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,q=0;q<g;q++)k=e[q],d+=M$({note:k,post:a.post,Jga:a.note.author.userId==k.author.userId},0,c);e=d;a.YJ?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.cq({user:c.currentUser,Ze:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',q=z.n("Send"),q=(0,z.y)(""+q),g=g(d+z.A(z.Gn({action:"save-reply",isPrimary:!0,text:(0,z.O)(""+z.A(q))},0,c))+z.A(z.Gn({action:"hide-reply-editor",text:(0,z.O)(""+z.A(J4a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.YJ?(d=z.y,q=z.n("Reply"),q=(0,z.y)(""+q),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.Gn({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.O)(""+z.A(q))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+M4a({note:a.note,isPrimary:!0,rga:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},M4a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.rga?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.rga?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.Gn({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.O)(""+a)},0,b)))},N4a=function(a,b,c){b="";if(0==a.G6)a=1==a.KC?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.KC)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Si(z.sm({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.G6)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Si(z.sm({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.G6){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign in to create a profile");b+=z.A(z.Q({rb:!0,Yb:!0,source:"highlight_tip",s:(0,z.O)(""+d),href:(0,z.M)(""+z.G(z.jl(c)))},c))+" "+a}return(0,z.y)(b)},N$=function(a,b,c,d,e,g,k,l){z.R.call(this);this.ra=a;this.xa=a.get("butter-bar");this.eb=b;this.Le=c;this.Nj=e;this.ve=a.get("quotes-data");this.tf=a.get("notes-data");this.nj=a.get("responses-data");this.hf=g;this.OZ=d;this.L_=(this.pG=k)?k.Si():null;this.Nf=this.Jc=null;this.Qj={};this.jaa=!!z.Pu();this.laa=!!z.Ru();this.Iz=this.jaa&&
this.laa&&z.rI(b);this.qq=null;this.eN=0;this.mda=S3a(this.ve,this.Le);this.Lv=l;this.Ua(this.qv());this.jba=z.Pu()?2:3},O4a=function(a){a.ob(".js-block").forEach(function(a){this.Pa(a,"mouseenter",this.ira,this);this.Pa(a,"mouseleave",this.b1,this)},a)},P4a=function(a){a.ob(".js-note").forEach(function(a){this.Pa(a,"mouseenter",this.gra,this);this.Pa(a,"mouseleave",this.b1,this)},a)},Q4a=function(a,b){var c=a.query(".js-note-"+b);a.Qj[b]||(a.Qj[b]=new L$(a.ra,c.querySelector(".js-replyEditor"),a.eb.La(),
b,a.Le),z.WA(a,a.Qj[b],"saving",a.Bua,a),z.WA(a,a.Qj[b],"save",a.vua,a),z.WA(a,a.Qj[b],"fail",a.wta,a));z.nd(c,"is-noteEditorVisible");a.Qj[b].focus()},R4a=function(a,b){var c=a.Qj[b];c&&(c.jb()&&c.rd(""),a=a.query(".js-note-"+b),z.qd(a,"is-noteEditorVisible"))},S4a=function(a,b,c){var d=I$(a.hf,a.Le);if(d){var e=[];a.Lv&&(e=a.Lv.quotes.map(function(a){return a.Si()}));(0,z.zb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),d=z.Va(d,b);if(this.Lv)var l=
a.getAttribute("name").split(" "),d=d&&(0,z.Wc)(l,z.Va.bind(null,e));z.sd(a,"is-selected",c&&d)},a)}},O$=function(a){return(a=z.uw(a,function(a){return z.md(a,"js-note-item")}))&&a.getAttribute("data-note-id")},T4a=function(a,b,c,d){b=new z.mH(b,300);b.Ua(c);b.subscribe("dismiss",d,a);b.qa();return b},P$=function(a){var b=a.hc(),c=a.Bd();a=a.ze();1<b.length&&(a=b[0].Ga().length);var d=new z.Zx;d.Jp(b[0].getName());d.Hg(c);z.K(d,"endIndex",a);d.rd(b[0].Ga().substring(c,a));return d},Q$=function(a,
b){b%=a.jba;0>b&&(b=a.jba-1);a.eN=b;(b=a.query(".js-highlightTip"))&&z.Vz(b,N4a,{G6:a.eN,KC:a.mda})},R$=function(a,b,c,d){z.R.call(this);this.Ua(this.qv(d));this.Hb=a.get("dom-monitor");this.eb=b;this.qaa=!b.Wa().Xq()||b.Lb();this.kb=b.La();this.hf=c;this.ve=a.get("quotes-data");this.nj=a.get("responses-data");this.tf=a.get("notes-data");this.uv=null;this.Ih={}},U4a=function(a,b){b.forEach(function(a){a&&S$(this,a)},a)},S$=function(a,b){if(!a.uv)if(I$(a.hf,b)){var c=V4a(a,b),c=W4a(a,c),c=X4a(a,c),
c=Y4a(a,c);a.Ih[b]=c;Z4a(a,b)}else delete a.Ih[b]},$4a=function(a,b){if(!a.uv){var c=a.Ih[b];if(c){var d=c.length,c=X4a(a,c),c=Y4a(a,c);a.Ih[b]=c;d!=c.length?Z4a(a,b):c.forEach(function(a){a.Va&&a.offsetTop&&(a.Va.style.top=a.offsetTop+"px")})}}},a5a=function(a,b,c){return z.Ta(a.Ih[b]||[],function(a){return a.Va==c})},V4a=function(a,b){var c=[];E$(a.tf,b).Tg(function(a){var e=a.rB(),g;e?(g=this.tf.fR(e),e=g.hb(),g=z.J(g,"endIndex")):(e=0,g=a.jb().length);c.push({anchor:b,startIndex:e,endIndex:g,
notes:[a],quotes:[],responses:[]})},a);if(a.qaa)return c;(a.ve.kt[b]||[]).forEach(function(a){var e=b5a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);s$(a.nj,b).forEach(function(a){var e=q$(a);e&&(e=r$(e)&&r$(e).En())&&(e=b5a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},W4a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});b.forEach(function(a){var b=
z.Sa(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.LF(c[b],a):c.push(a)},a);return c},Y4a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Sa(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.LF(c[b],a):c.push(a)}},a);return c},Z4a=function(a,b){a.ob(".js-paragraphControl-"+b).forEach(z.qh);a.Ih[b]=a.Ih[b].map(function(a){var b=c5a(this,a),b=z.Xz(d5a,b);b.style.top=a.offsetTop+"px";a.Va=b;this.na().appendChild(a.Va);
z.nd(b,"is-visible");return a},a)},c5a=function(a,b){var c=b.notes,d=b.responses,e=m$(a.ve,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,q=0,r=0,u=!1,v=!1,C={},H={},P=z.Ou().userId,N=a.eb.Wa().Ff().mb();c.forEach(function(a){var b=a.ZH();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==P&&l++,a.author.social&&a.author.social.isFollowing&&(C[a.author.userId]=a.author),H[a.author.userId]=!0)}),H[b.userId]=!0,b.userId==P&&l++,b.userId==N?q++:r++,b.social&&b.social.isFollowing&&
(C[b.userId]=b))});e.forEach(function(a){a=a.user;H[a.userId]=!0;a.userId==P&&(u=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});d.forEach(function(a){a=a.Ff();H[a.userId]=!0;a.userId==P&&(v=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.kb,HA:b.anchor,FFa:k,uGa:g,Ux:v,Lx:l,Cha:q,GFa:r,iYa:e.length,Sx:u,kga:Object.keys(H).length,yDa:z.lb(C),KC:c.length}},b5a=function(a){var b=a.Bd(),c=a.ze();1<a.paragraphs.length&&(c=
a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},X4a=function(a,b){var c=z.sA();return b.map(function(a){var b=this.hf.get(a.anchor),g=this.eb.Ri(b);if(!g)return a;var k;4==g.type&&(g.Ga()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.GFa))if(3==l.nodeType){var q=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=q.length}else if(l.nodeName in z.FS)k+=z.FS[l.nodeName].length;else for(q=
l.childNodes.length-1;0<=q;q--)b.push(l.childNodes[q]);k=l}g=z.vA(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},d5a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.HA)+' u-noUserSelect"\x3e',e=z.y,g;if(a.FFa||a.uGa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.HA)+'"\x3e';var k;k={};k=(0,z.y)(z.zo(z.D({name:"asteriskFilled",size:"19px",content:(0,z.O)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",q="",r=1==a.Lx?z.n("a note"):z.n("notes"),q=q+(""+r),q=z.E(q);1==a.kga&&(0<a.Lx||a.Sx||a.Ux)&&(0<a.Lx&&a.Sx&&a.Ux?(q=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):0<a.Lx&&a.Ux?(q=z.n("responded and left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):0<a.Lx&&a.Sx?(q=z.n("highlighted and left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):a.Sx&&a.Ux?(q=z.n("highlighted and responded"),l+=" "+q):a.Sx?
(q=z.n("highlighted"),l+=" "+q):0<a.Lx?(q=z.n("left {$noteCountText}",{noteCountText:""+q}),l+=" "+q):a.Ux&&(q=z.n("responded"),l+=" "+q));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';q="";if(0<a.Cha&&0==a.GFa&&!a.Sx&&!a.Ux)c=1==a.Cha?z.n("Note to self"):z.n("Notes to self"),q+=c;else{r="";if(0<a.KC)var u=z.n("Top highlight"),r=r+u;q+=z.A(z.DR(z.D({social:a.yDa,isActive:0<a.Lx||a.Sx||a.Ux,zi:a.kga,l4:!0,RFa:!0,Nea:(0,z.O)(r)},a),c));q+=z.A(l)}q=(0,z.O)(q);k+=z.A(z.TDa(z.D({text:q},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},T$=function(a,b,c){z.R.call(this);this.ra=a;this.Ia=a.get("app");this.Mpa=a.get("floating-components");this.Ma=a.get("screen");this.tb=a.get("screen-service");this.Hb=a.get("dom-monitor");this.eb=b;this.Pd=b.Pd;this.Tl=this.Pd.querySelector(".js-postField");this.Bba=this.Ma.na().querySelector(".js-notesPositionContainer");this.ve=a.get("quotes-data");this.tf=a.get("notes-data");this.tf.subscribe("new_note_list",this.Sta,this);
this.nj=a.get("responses-data");this.Sl=null;this.hf=new y4a(this.Pd.querySelector(".js-notesSource"));this.JF=this.Ih=this.aP=null;this.Ih=new R$(a,b,this.hf,this.Bba);this.track(this.Ih);this.JF=this.Ih.na();this.Lg=this.lZ=null;this.Me=c},V$=function(a,b){if(a.isActive()){var c=(b=b||a.lZ)&&b.JR,d=b&&b.noteId;c&&(a.hw(c),d&&a.tf.pp(d,c)&&a.Lg&&z.t(a.Lg,function(){return U$(a,c,null,d)}));z.yla(a.Ia,"")}else a.lZ=b||null},U$=function(a,b,c,d,e,g){var k={Ej:!0,f4:z.aA()};a.U_();c=new N$(a.ra,a.eb,
b,d||"",c||null,a.hf,e||null,g||null);c.subscribe("set-active-highlight",a.uca,a);c.subscribe("reset-highlight",a.bxa,a);c.subscribe("close",a.U_,a);b=g&&g.Va?g.Va:a.hf.get(b);g=z.Pta(a.Mpa);g.pn=b;b=g.QC(c);b.hH=k;k=b.zU(a.gn.bind(a));k.UO=!0;a.Sl=k.qa()},e5a=function(a,b,c){var d=a.eb.Ri(I$(a.hf,b));if(d&&4!=d.type){z.bx(d,4);if(c){if(!u4a(c,d))return;z.$w(d,z.Kw(c.startIndex,c.endIndex,c.id))}c=a.eb.Lb();var e=a.eb.Wa();c={mode:c?"edit":"view",Cj:z.ox(e),media:null,Gl:null,sections:!0,qk:!1,lk:!1,
jl:!1,Pf:!1,postId:e.id};a.hf.get(b).innerHTML=z.Mx(d,z.Cr,c)}},f5a=function(a,b){var c=z.Ds();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Sf();var d=A4a(a.hf,b);if(!d)return null;a=(b=z.uw(b,z.UD,d))&&a.eb.Ri(b);if(!b)return null;var d=z.xA(c,b,!0),e=z.xA(c,b,!1);return-1==d||-1==e?null:new v4a(c,b,new z.Zx({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ga().substring(d,e)}))},g5a=function(){},W$=function(a,b){z.R.call(this);this.Lh=b||a4a;this.fb=a.get("screen-request");
this.ua=null;this.l1=a.get("screen-view-state");this.ra=a;this.Ica=this.t0=!1;this.i_=this.Jc=null},X$=function(a){z.UA.call(this);this.uy=a},h5a=function(a,b,c){a=z.qa(a)?new z.Td(a):a;(a=r4a(a,b,c||{}))&&(new X$(a)).focus()},i5a=function(a){this.oa=a.get("request");this.la=a.get("route-builder")},j5a=function(a,b){b=new z.al(b.authBaseUrl);return new z.Td(b.mm(a))},k5a=function(a,b,c){b.content=b.content.replace(/“/g,"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’");var d=String(a(b,null,
c)),e=Y$(d)-140;0<e&&(b.content=z.xj(b.content,b.content.length-e),d=String(a(b,null,c)));return d},Y$=function(a){var b=a.length;a=a.match(l5a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},Z$=function(a){z.Dr.call(this);this.ra=a;this.oE=a.get("dialog");this.oa=a.get("request");this.la=a.get("route-builder");this.xa=a.get("butter-bar");this.oH=this.Ea=this.zw=this.ua=null;this.jN=!1},n5a=function(a){var b=a.Ea.query(".js-tweetEditor-image"),c=a.Ea.query(".js-tweetEditor-imageContainer"),
d=a.Ea.query(".js-tweetEditor-imageStatus");z.nd(c,"u-hide");var e=m5a(a);e.base64=!0;z.w(z.t(a.oa.post(z.Wz(d4a),e,{IA:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.qd(c,"u-hide");z.nd(d,"u-hide");this.jN=!0},a),function(a){z.QA(a);z.Vz(d,f4a)},a)},o5a=function(a,b){return 140>=Y$(b)?!0:(b=a.Ea.query(".js-tweetEditor-text"),(new z.iB(b,{name:"shimmy-shake",duration:400})).start(),a=a.Ea.query(".js-tweetEditor-error"),z.Vz(a,j4a),!1)},m5a=function(a){var b=a.ua,c=a.zw.zHa;
a=a.zw.yHa;var d=b.creator,e=b.approvedHomeCollection,g=z.Cr,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var q=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(q=e.tintColor);var r=null;e&&e.tintColor&&(r=z.tFa(e.tintColor),r=z.kw(r,.6).color);return new v$({content:c,altText:a,title:b.title,author:d&&d.name,date:z.ej(b.createdAt,g),authorAvatarId:d&&d.imageId,collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:q,
collectionHighlightColor:r,version:2})},p5a=function(a){this.oa=a.get("request");this.la=a.get("route-builder");this.ra=a},$$=function(a,b){z.ZZ.call(this);this.Ia=a.get("app");this.la=a.get("route-builder");this.Ha=a.get("model-request");this.ya=a.get("model-store");this.kb=b},q5a=function(a){var b=a.la.ka(z.pva,null,{sourcePostId:a.kb});return z.w(z.t(z.HP(a.Ha,C$,b),function(b){b=a.ya.kc(b);if(b=b.streamItem)b=z.Xz(b4a,{placements:b.welcomeContentFirst.placements}),z.rh(b,a.na()),a.Ua(b)}),z.QA)};
z.p(k$,z.L);z.f=k$.prototype;z.f.ba=function(){return""};z.f.ca=function(){return"Placement"};z.f.zg=function(){return z.J(this,"items")};z.f.Wc=z.h(408);z.f.tC=function(a){return z.K(this,"location",a)};z.f.Sd=z.h(458);z.f.Sb=function(a){return z.K(this,"index",a)};z.f.fa=function(){return k$.prototype};z.f.ea={name:"Placement",ha:!1,fields:{items:{name:"items",g:function(){return z.hO},pa:z.T,h:1},location:{name:"location",g:function(){return z.Ywa},h:2},index:{name:"index",g:z.V,h:3}},ia:{}};
z.f.Sd=z.X(458,function(){return z.J(this,"index")});z.f.Wc=z.X(408,function(a){return z.K(this,"items",a)});z.m(n$,z.Me);n$.prototype.ek=function(a){var b={};z.SG(this,b,a.Jb(),"");return b};
n$.prototype.Gb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.Pj(g,k);if(!l)break;var q=l.g();if(l.pa()){var r=z.Kj(g,k)||[],u=e.shift(),v=Number(u);if(void 0===u||!Number.isInteger(v)||0>v)break;if(q.prototype instanceof z.Ej)l=r[v],l||(l=new q,r[v]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;q=L3a(b[a],l);r[v]=q;z.K(g,k,r)}}else if(q.prototype instanceof z.Ej)r=z.Kj(g,
k),r||(r=new q,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;q=L3a(b[a],l);z.K(g,k,q)}k=e.shift()}});return c};z.p(o$,z.jk);z.f=o$.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.vB=z.h(455);z.f.fa=function(){return o$.prototype};z.f.ea={name:"PlacementsResponse",ha:!1,fields:{placements:{name:"placements",g:function(){return k$},pa:z.T,h:1}},ia:{}};z.p(p$,z.L);p$.prototype.ba=function(){return""};p$.prototype.ca=function(){return""};p$.prototype.fa=function(){return p$.prototype};
p$.prototype.ea={name:"PlacementsRequestQuery",ha:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.cv},h:1},slots:{name:"slots",g:function(){return z.ev},pa:z.T,h:2}},ia:{}};z.eY.prototype.QT=z.X(610,function(a){a!=this.sN&&this.vb&&(this.vb.ci.contentEditable=a);this.sN=a});z.ZI.prototype.f3=z.X(602,function(a){a=q$(a);if(!a)return null;a=r$(a)&&r$(a).En();return a?(a=a.hc())&&a.length?a[0].getName():null:null});z.rH.prototype.zU=z.X(601,function(a){this.gn=a;return this});
z.lJ.prototype.zU=z.X(600,function(a){this.gn=a;return this});z.tB.prototype.pp=z.X(511,function(){return z.J(this,"note")});z.MG.prototype.pp=z.X(510,function(a){return this.oc("Note",a)});z.Yx.prototype.fx=z.X(490,function(){return z.J(this,"replyId")});z.tB.prototype.fx=z.X(489,function(){return z.J(this,"replyId")});z.Wx.prototype.by=z.X(488,function(a){return z.K(this,"highlight",a)});z.Wx.prototype.fR=z.X(487,function(){return z.J(this,"highlight")});
z.Wx.prototype.Ku=z.X(486,function(a){return z.K(this,"author",a)});z.Yx.prototype.Ku=z.X(485,function(a){return z.K(this,"author",a)});z.Wx.prototype.ZH=z.X(484,function(){return z.J(this,"author")});z.Yx.prototype.ZH=z.X(483,function(){return z.J(this,"author")});z.Wx.prototype.rB=z.X(482,function(){return z.J(this,"highlightId")});z.Wx.prototype.fy=z.X(481,function(a){return z.K(this,"state",a)});z.Yx.prototype.fy=z.X(480,function(a){return z.K(this,"state",a)});
z.nB.prototype.fy=z.X(479,function(a){return z.K(this,"state",a)});z.Wx.prototype.Ag=z.X(478,function(){return z.J(this,"noteId")});z.Yx.prototype.Ag=z.X(477,function(){return z.J(this,"noteId")});z.tB.prototype.Ag=z.X(476,function(){return z.J(this,"noteId")});z.Qv.prototype.Lu=z.X(471,function(a){return z.K(this,"authorId",a)});z.Wx.prototype.Lu=z.X(470,function(a){return z.K(this,"authorId",a)});z.Yx.prototype.Lu=z.X(469,function(a){return z.K(this,"authorId",a)});
z.cN.prototype.vB=z.X(456,function(){return z.J(this,"placements")});o$.prototype.vB=z.X(455,function(){return z.J(this,"placements")});z.TG.prototype.vB=z.X(454,function(a,b){var c=this;a=N3a(O3a(new p$,a),b);a=(new n$).ek(a);var d=this.la.ka(z.cva,{},a);return z.UG(this,d,function(){return z.t(c.oa.get(d,{background:!0}),function(a){a=c.Ha.$b(o$,a);c.ya.kc(a);return a})})});z.Du.prototype.oe=z.X(370,function(){return z.J(this,"catalogId")});z.uM.prototype.oe=z.X(369,function(){return z.J(this,"catalogId")});
z.mM.prototype.oe=z.X(368,function(){return z.J(this,"catalogId")});z.kM.prototype.oe=z.X(367,function(){return z.J(this,"catalogId")});z.hO.prototype.oe=z.X(366,function(){return z.J(this,"catalogId")});z.PL.prototype.oe=z.X(365,function(){return z.J(this,"catalogId")});z.MN.prototype.oe=z.X(364,function(){return z.J(this,"catalogId")});z.JM.prototype.oe=z.X(363,function(){return z.J(this,"catalogId")});z.EN.prototype.oe=z.X(362,function(){return z.J(this,"catalogId")});
z.DN.prototype.oe=z.X(361,function(){return z.J(this,"catalogId")});z.CN.prototype.oe=z.X(360,function(){return z.J(this,"catalogId")});z.Qv.prototype.oe=z.X(359,function(){return z.J(this,"catalogId")});z.YO.prototype.oe=z.X(358,function(){return z.J(this,"catalogId")});z.tB.prototype.oe=z.X(357,function(){return z.J(this,"catalogId")});z.MJ.prototype.oe=z.X(356,function(){return z.J(this,"catalogId")});z.pt.prototype.pR=z.X(82,function(){return z.J(this,"point")});
t$.prototype.pR=function(){var a=window.document.body;return z.xh(a,this.ji.node)?this.ji:this.Ek&&z.xh(a,this.Ek)?z.uP(this.eO,this.Ek):this.Le&&(a=z.xw(this.Ipa,this.Le))?z.uP(this.eO,a):null};z.p(u$,z.Qr);u$.prototype.yJ=function(){if(!this.Tj)return null;var a=this.Tj.pR();if(!a)return null;var b=this.Wl.pR();return b?z.qs(a.node,a.offset,b.node,b.offset):null};z.p(v$,z.L);z.f=v$.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.jb=function(){return z.J(this,"content")};
z.f.rd=function(a){return z.K(this,"content",a)};z.f.Cb=function(){return z.J(this,"title")};z.f.Nc=function(a){return z.K(this,"title",a)};z.f.ZH=function(){return z.J(this,"author")};z.f.Ku=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Db=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.VJ=function(a){return z.K(this,"template",a)};
z.f.Td=function(){return z.J(this,"subtitle")};z.f.xf=function(a){return z.K(this,"subtitle",a)};z.f.fa=function(){return v$.prototype};
z.f.ea={name:"TextshotInfo",ha:!1,fields:{content:{name:"content",g:z.U,h:1},altText:{name:"altText",g:z.U,h:2},title:{name:"title",g:z.U,h:3},author:{name:"author",g:z.U,h:4},date:{name:"date",g:z.U,h:5},authorAvatarId:{name:"authorAvatarId",g:z.U,h:6},collection:{name:"collection",g:z.U,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.U,h:8},collectionLogoId:{name:"collectionLogoId",g:z.U,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.U,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.U,h:11},version:{name:"version",g:z.V,h:12},base64:{name:"base64",g:z.UJ,h:13},template:{name:"template",g:z.U,h:14},mainStat:{name:"mainStat",g:z.U,h:15},mainStatTitle:{name:"mainStatTitle",g:z.U,h:16},subtitle:{name:"subtitle",g:z.U,h:17},icon:{name:"icon",g:z.U,h:18},imgKey:{name:"imgKey",g:z.U,h:19}},ia:{}};z.p(x$,z.R);z.f=x$.prototype;z.f.fk=function(){return this.bm.fk()};
z.f.ma=function(){x$.va.ma.call(this);z.WA(this,this.cY,"data-redirect-type-quote",this.eta,this);this.Pa(this.Pd,"click",this.Ev,this);z.sI(this.eb)&&z.Zz()&&this.Pa(this.Pd,"mouseover",this.Aqa,this);this.eb.Wa().Xq()&&!this.eb.Lb()&&z.w(this.ve.load(this.eb.La()),z.QA);var a=this.fk();a&&(z.WA(this,a,"quote",this.vqa,this),z.WA(this,a,"quote-respond",this.wqa,this),z.WA(this,a,"show",this.d1,this),z.WA(this,a,"hide",this.xta,this))};
z.f.eta=function(a){var b=z.dI(this.bm,this.fk().ww);b&&(a.url=new z.Td(this.la.ka(z.nya,{postId:this.eb.La()},{paragraphs:JSON.stringify([b.mx.Gb().Jb()]),startOffset:b.start,endOffset:b.end})))};z.f.Ev=function(a){z.uw(a.target,function(a){if(a===this.Pd)return!0;var c=z.cE(a);if(3==c)return!0;if(7==c){if(c=n4a(this,a))if(y$(this,c),z.Zz())A$(this,c);else{var d=new z.mF;l4a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.Aqa=function(a){z.uw(a.target,function(a){if(a===this.Pd)return!0;var c=z.cE(a);if(3==c)return!0;if(7==c){c=z.Ds();if(!(c&&!c.isCollapsed()||this.fk()&&this.fk().zm())&&(c=n4a(this,a))){var d=this.Pd.querySelector('.markup--quote[name~\x3d"'+c.Si()+'"]');a=new z.mH(a,100);l4a(this,c,d,a);y$(this,c)}return!0}return!1}.bind(this))};
z.f.d1=function(){var a=z.Ds();a&&!a.isCollapsed()&&y$(this,null);z.sI(this.eb)&&(a=z.dI(this.bm,this.fk().ww))&&(a=z.Jra(this.ve,a.mx,a.start,a.end),z.sd(this.fk().Sa().querySelector(".js-highlightMenuQuoteButton"),"is-active",!!a))};z.f.xta=function(){this.Vo&&y$(this,null)};
z.f.vqa=function(){if(z.sI(this.eb)){var a=z.ZH(this.fk());if(a){var b=a.range,c=a.PEa,d=z.md(this.fk().Sa().querySelector(".js-highlightMenuQuoteButton"),"is-active"),a=z.dI(this.bm,b);z.w(z.t(this.ve.toggle(a.mx,a.start,a.end,!c),function(a){z.xFa();d?z.aI(this.fk()):A$(this,a);var b=c?"selection_menu":"quote_click_menu";B$(this,a.Si(),!d,b)},this),z.QA)}}};
z.f.wqa=function(){if(z.sI(this.eb)&&z.Cr.supportsEdit){var a=z.ZH(this.fk());if(a){var b=z.dI(this.bm,a.range);z.w(z.t(this.ve.create(b.mx,b.start,b.end,1,!0),function(a){B$(this,a.Si(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.mx.name)},this),z.QA)}}};
z.f.Hqa=function(a){var b=this.Vo,c=z$(this,b),d=b.Bd(),e=b.ze(),b=a.query(".js-quoteAttributions-pileOn"),g=z.md(b,"is-active");z.w(z.t(this.ve.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.td(l,"is-active");if(l=z.VH(this.ve,c,d,e)){var q=k4a(this,l),r=a.query(".js-quoteAttributions-info");z.Vz(r,X3a,q)}else a.Sc();!g&&z.Zz()&&(a.Sc(),A$(this,l));l=z.Zz()?"quote_hover":"quote_click_mobile";B$(this,b.Si(),!g,l)},this),z.QA)};
z.f.Iqa=function(){if(z.sI(this.eb)&&z.Cr.supportsEdit){var a=z$(this,this.Vo),b=this.Vo.Bd(),c=this.Vo.ze();z.w(z.t(this.ve.create(a,b,c,1,!0),function(b){B$(this,b.Si(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.QA)}};z.f.Jqa=function(){var a=p4a(this,this.Vo);a&&z.Tra(this.bm,a)};
z.f.jca=function(){var a=new u$(this.Pd),b=this.ve.kt,c=Object.keys(b).concat(this.J9);z.cb(c);c.forEach(function(a){var c=b[a]||[],g=this.eb;if(g=(a=g.Pd&&z.xw(g.Pd,a))&&this.eb.Ri(a))W3a(g,c),a.innerHTML=z.Mx(g,z.Cr,z.dsa(this.eb)),z.Yta(this.gwa,a)},this);this.J9=Object.keys(b);(a=a.restore())&&a.select()};z.p(C$,z.jk);C$.prototype.ba=function(){return""};C$.prototype.ca=function(){return""};C$.prototype.fa=function(){return C$.prototype};
C$.prototype.ea={name:"OnboardingWelcomeResponse",ha:!1,fields:{streamItem:{name:"streamItem",g:function(){return z.hO},h:1}},ia:{}};z.p(D$,z.UA);z.f=D$.prototype;z.f.load=function(a){if(!z.Pu())return z.$c([]);this.kb=a;this.Fh||(this.Fh=z.w(z.t(this.Yk.get(this.la.ka(z.fya,{postId:a}),{background:!0}),this.ewa,this),z.QA));return this.Fh.Zc()};z.f.zp=function(){return this.G9};z.f.gk=function(){return this.Iba};z.f.fR=function(a){return this.Y$[a]||null};
z.f.pp=function(a,b){return z.bQ(E$(this,b),a)};z.f.by=function(a,b){this.Y$[a]=b};z.f.La=function(){return this.kb};
z.f.ewa=function(a){var b=a.references.User;this.Iba=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var q=g[l],r=q.authorId||null;q.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=E$(this,g);e=z.Xx(e);g.add(z.OE(this.ya,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.by(a[b].id,z.it.Gb(z.Zx,a[b]));this.G9=!0};z.m(H$,z.R);H$.prototype.ma=function(){var a=this;z.R.prototype.ma.call(this);z.t(this.fb.vB(this.WO,this.Rva),function(b){b.placements&&b.placements.forEach(a.vra,a)})};
H$.prototype.vra=function(a){if(this.isActive()){var b=null;switch(a.location){case 1:b=this.Ma.query(".js-postFooterPlacements");if(!b)break;z.Vz(b,z.UR,{items:a.items,context:9});z.S(b).aa("show-more-recommendations",this.Dya,this);break;case 2:b=this.Ma.query(".js-readNextMetabarRight");if(!b)break;z.Vz(b,z.UR,{items:a.items,context:2});break;case 6:(b=this.Ma.query(".js-postPromotionWrapper"))&&z.Vz(b,z.UR,{items:a.items,context:2})}b&&w4a(this,b)}};
H$.prototype.Dya=function(a){z.yB(z.TBa,{});var b=this.Ma.query(".js-moreRecommendations");b&&(z.Aw(b),z.zw(a.target))};x4a.prototype.xQ=function(a,b,c){return new x$(a,b,c)};y4a.prototype.get=function(a){return I$(this,a)};z.p(J$,z.eY);z.f=J$.prototype;z.f.IG=!1;z.f.Fz="";z.f.JG=0;z.f.Bp=z.T;z.f.Ag=function(){return this.OZ};z.f.save=function(){this.jb().length<=this.am&&this.$k()};z.f.Ib=function(){(0,window.clearTimeout)(this.JG);J$.va.Ib.call(this)};
z.f.ma=function(){function a(a){a.stopPropagation()}J$.va.ma.call(this);this.Fz=this.jb();this.rd(this.Fz);this.Hw(13,this.WZ,this);this.Hw(27,this.XZ,this);this.vb.Pa("blur",this.VZ,!1,this);var b=this.vb.Sa();z.kA(b,"keydown",a);z.kA(b,"keyup",a);z.kA(b,"keypress",a)};z.f.l5=function(a){return a};
z.f.$k=function(){if(this.isEnabled()){var a=this.jb().trim();if(a){this.QT(!1);var b=this.Gfa(),a=this.Ffa(a);this.za("saving",a);z.Rc(z.w(z.t(this.Yk.post(b,a.Jb()),this.Wta,this),this.Uta.bind(this,a)),this.QT.bind(this,!0))}}};z.f.Wta=function(a){this.za("save",this.l5(a.value))};z.f.Uta=function(a,b){this.za("fail",a);this.Ea.error(B4a());z.QA(b)};z.f.WZ=function(a){if(this.yt&&z.TY(this.yt))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.XZ=function(a){if(this.yt&&z.TY(this.yt))return!1;a.preventDefault();this.rd(this.Fz);this.za("cancel");return!1};z.f.VZ=function(){this.IG&&(this.jb().length>=this.am?(0,window.confirm)(this.Ifa())?(this.rd(this.Fz),this.za("cancel")):this.focus():this.JG=(0,window.setTimeout)(this.$k.bind(this),100))};z.p(K$,J$);z.f=K$.prototype;z.f.hW=null;z.f.X8=null;z.f.iW=null;z.f.Nj=null;z.f.wY=null;z.f.vY=null;z.f.X$=null;z.f.by=function(a){this.Nj=a;this.wY=a.startIndex;this.vY=a.endIndex;this.X$=a.content;return this};z.f.Ifa=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.l5=function(a){var b=z.Tz();a=z.Xx(a).Ku(b).Lu(b.mb());this.Nj&&a.rB()&&this.tf.by(a.rB(),this.Nj);var b=this.tf,c;c=z.OE(b.ya,a);E$(b,c.ne()).add(c);return a};
z.f.Gfa=function(){return this.Ag()?this.la.ka(z.gya,{postId:this.kb,noteId:this.Ag()}):this.la.ka(z.eya,{postId:this.kb})};z.f.Ffa=function(a){var b=z.Tz();a=(new z.Wx({content:a,anchor:this.hW,anchorContent:this.X8,anchorImage:this.iW?this.iW.Jb():null,replies:[],createdAt:Date.now()})).Ku(b);null!=this.wY&&null!=this.vY&&(b=new z.Zx({anchor:this.hW,startIndex:this.wY,endIndex:this.vY,content:this.X$}),a.by(b));return a};z.p(L$,J$);L$.prototype.Ifa=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};L$.prototype.l5=function(a){var b=z.Tz();a=z.jia(a).Ku(b).Lu(b.mb());z.J(this.tf.pp(a.Ag(),this.Le),"replies").push(a);return a};L$.prototype.Gfa=function(){return this.fca?this.la.ka(z.jya,{postId:this.kb,noteId:this.Ag(),replyId:this.fca}):this.la.ka(z.iya,{postId:this.kb,noteId:this.Ag()})};
L$.prototype.Ffa=function(a){var b=z.Tz();return(new z.Yx({replyId:"",postId:this.kb,noteId:this.Ag(),content:a,createdAt:Date.now()})).Ku(b)};z.p(N$,z.R);z.f=N$.prototype;
z.f.ma=function(){N$.va.ma.call(this);z.S(this.na()).aa("show-note-editor",this.y0,this).aa("hide-note-editor",this.sY.bind(this,!0)).aa("show-reply-editor",this.Rya,this).aa("hide-reply-editor",this.dra,this).aa("save-note",this.sxa,this).aa("save-reply",this.uxa,this).aa("highlight-quote",this.hra,this).aa("dismiss-note",this.N9.bind(this,!0),this).aa("delete-note",this.N9.bind(this,!1),this).aa("delete-reply",this.Roa,this).aa("previous-highlight-tip",this.cwa,this).aa("next-highlight-tip",this.Jsa,
this);P4a(this);this.nj&&l$(this.nj)&&(O4a(this),z.WA(this,l$(this.nj),"add",this.Tta,this));if(this.L_&&this.jaa&&this.laa){var a=this.query(".js-inlineNewPostControl"),b=this.L_,c=this.eb.La(),d=new z.hU(this.ra);d.KJ("web-inline-quote-responses");d.Ua(a);d.qE=!0;d.mX=!0;d.kX=!0;d.VJ(Y3a);d.Ez=b;d.OJ(c);z.iU(d,!0);this.Jc=d;this.Jc.qa();a=P$(this.pG);this.za("set-active-highlight",this.Le,a)}this.Nj&&(this.y0(),this.Nf&&this.Nf.focus());Q$(this,0)};
z.f.Aa=function(){this.qq&&this.qq.r2();(this.Nj||this.pG)&&this.za("reset-highlight",this.Le,null);N$.va.Aa.call(this)};z.f.Ib=function(){z.GB(this.na());z.qh(this.na());z.Fr(this.Jc);z.Fr(this.Nf);z.Fr(this.qq);z.Gr(z.lb(this.Qj));this.qq=this.Qj=this.Nf=this.Jc=null;N$.va.Ib.call(this)};z.f.Kn=function(){if(this.Nf&&this.Nf.jb())return!0;for(var a=z.lb(this.Qj),b=0;b<a.length;b++)if(a[b]&&a[b].jb())return!0;return this.Jc&&!this.Jc.isDismissable()?!0:!1};
z.f.qv=function(){var a=[],b=[],c=[],d=this.Iz&&(this.Nj||this.pG);d||(this.Lv?(a=this.ve?m$(this.ve,this.Lv.quotes):[],b=this.Lv.notes,c=this.Lv.responses):(b=this.tf?z.XE(E$(this.tf,this.Le)):[],this.OZ||(this.ve?(a=this.ve,a=m$(a,a.kt[this.Le]||[])):a=[],c=this.nj?s$(this.nj,this.Le):[])));return z.Xz(L4a,{post:this.eb.Wa(),quotes:a,notes:b,responses:c,T6:!!this.L_,$T:d,YJ:this.Iz,KC:this.mda,HFa:z.rI(this.eb)})};
z.f.Tta=function(){var a=this.query(".js-postList"),b=z.Xz(K4a,{responses:s$(this.nj,this.Le)});z.rh(b,a);O4a(this)};
z.f.y0=function(){if(this.Iz){if(!this.Nf){var a=this.query(".js-noteEditor"),b=z.Wz(I4a),a=this.Nf=new K$(this.ra,a,this.eb.La(),null,b),b=this.Le,c=this.eb.Ri(this.hf.get(this.Le)),d=c.Ga(),c=4==c.type?c.Ae():null;a.hW=b;a.X8=d;a.iW=c;(a=this.Nj)&&this.Nf.by(a);z.WA(this,this.Nf,"saving",this.Aua,this);z.WA(this,this.Nf,"fail",this.vta,this);z.WA(this,this.Nf,"save",this.uua,this)}z.nd(this.query(".js-noteActions"),"is-noteEditorVisible");this.Nf&&this.Nf.focus()}};z.f.sxa=function(){this.Nf&&this.Nf.save()};
z.f.Aua=function(a){this.Nf.rd("");var b=this.query(".js-notesList");a={note:a,post:this.eb.Wa(),$T:this.Iz,YJ:this.Iz};a=z.Xz(M$,a);b.appendChild(a);z.qd(b,"is-empty");P4a(this);this.sY()};z.f.uua=function(a){var b=this.query(".js-notesList").lastChild;a=a.Ag();z.nd(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};z.f.vta=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.nd(a,"is-empty");this.y0()};
z.f.sY=function(a){a?this.za("close"):this.Nf&&(this.Nf.jb()&&this.Nf.rd(""),z.qd(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.Rya=function(a){(a=O$(a.target))&&this.Iz&&Q4a(this,a)};z.f.uxa=function(a){a=O$(a.target);(a=this.Qj[a])&&a.save()};
z.f.Bua=function(a){var b=a.Ag();this.Qj[b]&&this.Qj[b].rd("");var c=this.tf.pp(b,this.Le).author.userId==a.author.userId,d=this.query(".js-note-"+a.Ag()+" .js-repliesList");a={note:a,post:this.eb.Wa(),Jga:c};a=z.Xz(M$,a);d.appendChild(a);z.qd(d,"is-empty");R4a(this,b)};z.f.vua=function(a){var b=this.query(".js-note-"+a.Ag()).querySelector(".js-repliesList").lastChild;a=a.fx();z.nd(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.wta=function(a){var b=this.query(".js-note-"+a.Ag()+" .js-repliesList");b.removeChild(b.lastChild);z.nd(b,"is-empty");Q4a(this,a.Ag())};z.f.dra=function(a){(a=O$(a.target))&&R4a(this,a)};z.f.hra=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=I$(this.hf,this.Le);c&&(this.qq&&this.qq.r2(),this.qq=T4a(this,c,a,function(){S4a(this,b,!1);z.Fr(this.qq);this.qq=null}),S4a(this,b,!0))};
z.f.gra=function(a){var b=I$(this.hf,this.Le);(a=this.tf.pp(a.target.getAttribute("data-note-id"),this.Le))&&b&&(b=(b=a.rB())?this.tf.fR(b):null,this.za("set-active-highlight",this.Le,b))};z.f.ira=function(a){var b=I$(this.hf,this.Le),c;c=this.nj;a=a.target.getAttribute("data-post-id");c=l$(c)?z.bQ(l$(c),a):null;b&&c&&(b=q$(c))&&(b=r$(b)&&r$(b).En())&&(c=b.hc())&&c.length&&(b=P$(b),this.za("set-active-highlight",this.Le,b))};
z.f.b1=function(){var a=null;this.pG&&(a=P$(this.pG));this.Nj&&(a=this.Nj);this.za("reset-highlight",this.Le,a)};
z.f.N9=function(a,b){b=b.value;var c=this.tf.pp(b,this.Le),d=this.query(".js-note-"+b);if(c&&d){z.zw(d);this.b1();this.ob(".js-note-item").every(function(a){return z.md(a,"u-hide")})&&this.sY(!0);var e=F$(this.tf,c,"HIDDEN");z.w(e.ll,function(b){this.xa.qa(a?C4a():D4a(),"error");e.zJ();z.Aw(d);(400>b.status||499<b.status)&&F$(this.tf,c,"NEW")},this);z.t(this.xa.qa(a?F4a():G4a(),{type:"success",OC:!0}),function(){this.xa.Sc();e.zJ();F$(this.tf,c,"NEW");z.Aw(d)},this)}};
z.f.Roa=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=O$(a.target);if(d&&c){z.zw(c);var e=G$(this.tf,b,d,this.eb.La(),this.Le,"HIDDEN");z.w(e.ll,function(){this.xa.qa(E4a(),"error");e.zJ();z.Aw(c);G$(this.tf,b,d,this.eb.La(),this.Le,"")},this);z.t(this.xa.qa(H4a(),{type:"success",OC:!0}),function(){this.xa.Sc();e.zJ();G$(this.tf,b,d,this.eb.La(),this.Le,"");z.Aw(c)},this)}};z.f.cwa=function(){Q$(this,this.eN-1)};z.f.Jsa=function(){Q$(this,this.eN+1)};z.p(R$,z.R);z.f=R$.prototype;z.f.ma=function(){R$.va.ma.call(this);var a=[];z.rI(this.eb)&&a.push(this.tf.load(this.kb));this.qaa||(a.push(this.ve.load(this.kb)),a.push(this.nj.load(this.kb)));this.uv=z.t(z.t(z.t(z.cT(a),function(){this.uv=null},this),this.Jr,this),this.Kna,this);z.WA(this,this.Hb,"resize-end",this.kg,this)};z.f.Aa=function(){this.uv&&this.uv.cancel();R$.va.Aa.call(this)};z.f.Ib=function(){this.uv=null;R$.va.Ib.call(this)};z.f.Jr=function(){z4a(this.hf,function(a,b){S$(this,b)},this)};
z.f.kg=function(){z4a(this.hf,function(a,b){$4a(this,b)},this)};z.f.Kna=function(){var a=this.ve.Lo;z.WA(this,a,"add",this.qba,this);z.WA(this,a,"remove",this.qba,this);(a=l$(this.nj))&&z.WA(this,a,"add",this.rua,this)};z.f.qba=function(a){U4a(this,Object.keys(z.Nra(this.ve,a instanceof Array?a:[a])))};z.f.rua=function(a){U4a(this,(a instanceof Array?a:[a]).map(this.nj.f3,this.nj))};z.f.qv=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};
z.f.LF=function(a,b){z.vb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.p(T$,z.R);z.f=T$.prototype;
z.f.ma=function(){T$.va.ma.call(this);this.Pa(this.Ma.na(),"click",this.ksa,this,!0);z.S(this.JF).aa("select-anchor",this.Eua,this);var a=this.eb.Wa();if(a.Xq()&&!this.eb.Lb()){var b=z.wu(a),b=2==a.visibility&&b&&!z.J(b.zl(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.w(this.nj.load(this.eb.La(),"best"),z.QA);z.w(this.ve.load(this.eb.La()),z.QA)}a.zl().YH()&&(this.cO=z.t(this.tf.load(this.eb.La()),this.Xta,this));this.lZ&&V$(this,null);z.WA(this,this.tb,"historyUpdate",function(){V$(this,
z.gI())},this);this.Me&&z.WA(this,this.Me,"highlight",this.Vta,this)};z.f.Ib=function(){z.Fr(this.Ih);this.Ih=null;z.Fr(this.Sl);this.Sl=null;this.JF&&z.S(this.JF).clear("select-anchor");this.cO&&this.cO.cancel();this.cO=null;T$.va.Ib.call(this)};z.f.NFa=function(a,b){U$(this,b,null,null,a)};z.f.NHa=function(){this.Ih&&this.Ih.kg()};z.f.Kn=function(){if(!this.Sl)return!1;var a=this.Sl.jb();return a?a.Kn():!1};z.f.Sta=function(a){a.subscribe("add",this.uda,this);a.subscribe("remove",this.uda,this)};
z.f.uda=function(a){(z.oa(a)?a:[a]).forEach(function(a){S$(this.Ih,a.ne())},this)};z.f.Xta=function(){var a=(0,z.Ia)();this.cO=null;V$(this,z.gI());this.Pa(this.Tl,z.wK,this.f_,this);z.pC("notes.renderMarkers",(0,z.Ia)()-a)};z.f.f_=function(a){(a=a.target.getAttribute("name"))&&I$(this.hf,a)&&$4a(this.Ih,a)};z.f.Vta=function(){if(this.Me){var a=f5a(this,this.Me.ww);z.aI(this.Me);a&&(a=a.highlight,this.uca(a.anchor,a),U$(this,a.anchor,a))}};
z.f.ksa=function(a){if(this.Sl){var b=a.target;if(!z.xh(this.Sl.na(),b)){var c=this.Sl.jb(),d;if(!(d=!c)){a:if(c.Nf&&c.Nf.jb())c=!0;else{d=z.lb(c.Qj);for(var e=0;e<d.length;e++)if(d[e]&&d[e].jb()){c=!0;break a}c=c.Jc&&!c.Jc.Wi()?!0:!1}d=!c}d&&(c=this.Sl&&this.Sl.pn,d="select-anchor"==b.getAttribute("data-action"),this.U_(),c&&d&&z.xh(c,b)&&a.stopPropagation())}}};
z.f.gn=function(a){if(!z.aA()){var b=a.pn,c=z.vA(b);a.sl();a=a.na();var d=z.vA(a),e=window.innerHeight,g=window.innerWidth,k=this.Ma.query(".js-metabar"),l=0;k&&(l=z.vA(k).height);d.height>=e-l?s4a(a):(z.rA(b),b=c.top+d.height>=e?z.sA().top+e-d.height-10:z.rA(b),c=z.vA(this.JF).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.U_=function(){z.Fr(this.Sl);this.Sl=null};
z.f.Eua=function(a){var b=z.uw(a.target,function(a){return z.md(a,"js-paragraphControl")},this.Bba),b=a5a(this.Ih,a.value,b);U$(this,a.value,null,null,null,b)};z.f.uca=function(a,b){if(this.eb.Lb()){var c=z.Ds();this.aP=(c=c&&A4a(this.hf,c.Sf()))&&new u$(c)}e5a(this,a,b)};z.f.bxa=function(a,b){e5a(this,a,b);this.eb.Lb()&&this.aP&&(a=this.aP.restore())&&a.select();this.aP=null};
z.f.hw=function(a){if(this.hf&&(a=I$(this.hf,a))){a=Math.max(z.rA(a),0);var b=window.document.body;this.Lg&&this.Lg.cancel();this.Lg=new z.bA(b,"scrollTop",600,a)}};g5a.prototype.xQ=function(a,b,c){return new T$(a,b,c)};z.m(W$,z.R);z.f=W$.prototype;z.f.Ec=function(a){this.ua=a};z.f.VJ=function(a){this.Lh=a};z.f.RGa=function(a){this.t0=a};z.f.SGa=function(a){this.Ica=a};
z.f.ma=function(){this.na()?(z.R.prototype.ma.call(this),z.S(this.na()).aa("show-responses-stream-editor",this.Pua,this).aa("show-other-responses",this.Oca,this),z.Vz(this.na(),this.Lh,{post:this.ua}),this.ua.Xq()&&z.w(z.t(z.t(z.t(V3a(this.fb,this.ua.Bb(),"best"),this.dca.bind(this,"best")),this.Jwa,this),function(){this.l1.q6&&this.Oca()},this),z.QA)):z.QA("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Aa=function(){z.S(this.na()).clear("show-other-responses");z.R.prototype.Aa.call(this)};
z.f.dca=function(a,b){this.isActive()&&(b=b.ie,"best"==a?(a=this.query(".js-responsesStream"),z.WA(this,b,"add",this.Uaa.bind(this,b)),this.Uaa(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Ru()||0<b.Oe())&&a&&(z.Vz(a,z.UR,{items:z.XE(b),context:2}),b=new z.JU(this.ra,b),b.Ua(a),b.sd(2),this.track(b),z.Aw(this.query(".js-responsesStreamWrapper"))),this.Ica&&(a=z.rA(a),z.oA(window.document.body,0,a)))};
z.f.Jwa=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Ru()?a?(this.Jc=z.iU(P3a((new z.hU(this.ra)).KJ("web-inline-post-response").OJ(this.ua.Bb()),z.Uz(z.bl,{post:this.ua,DT:!0})),this.t0).Ua(a),this.track(this.Jc)):b&&this.t0&&(a=z.qA(b),b=z.rA(b),z.oA(a,0,b)):b&&z.nd(b,"u-hide")};
z.f.Oca=function(){this.i_||(this.i_=z.Rc(z.t(z.t(V3a(this.fb,this.ua.Bb(),"other"),this.dca.bind(this,"other")),function(){z.zw(this.query(".js-showOtherResponses"));this.l1.q6=!0},this),function(){this.i_=null},this))};z.f.Uaa=function(a){(a=a.Tk)&&a.next&&"other"==a.next.filter&&!this.l1.q6&&(z.Aw(this.query(".js-responsesStreamWrapper")),z.Aw(this.query(".js-showOtherResponses")))};z.f.Tw=function(){this.Jc&&(z.QS(this.Jc.na(),new z.Js(60,0,200,0)),this.Jc.Tw())};
z.f.Pua=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.tS(a)&&(z.Aw(a),z.zw(b),this.Tw())};z.p(X$,z.UA);X$.prototype.focus=function(){this.isActive&&this.uy.focus()};X$.prototype.close=function(){this.uy&&!this.uy.closed&&this.uy.close();this.za("close");this.ag()};X$.prototype.isActive=function(){return this.uy?!this.uy.closed:!1};X$.prototype.Ta=function(){this.uy=null;X$.va.Ta.call(this)};z.f=i5a.prototype;z.f.yC=function(a,b,c){var d;d=z.Cr;var e=new z.al(z.Br(d)),e=new z.Td(e.mm(a));d=w$(e,d);this.Sv(d);z.yB(z.gL,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.j6=function(a){var b;b=z.Cr;var c=new z.al(z.Br(b));a=new z.Td(c.ka(z.gz,{catalogSlug:a.oe(),username:a.Ff().ik()}));b=w$(a,b);this.Sv(b)};z.f.k6=function(a){var b;b=z.Cr;var c=new z.al(z.Br(b));a=new z.Td(c.ka(z.Yy,{sequenceSlug:a.pd()}));b=w$(a,b);this.Sv(b)};
z.f.b3=function(){var a=this.la.ka(z.Mxa);return this.oa.get(a)};z.f.Sv=function(a){h5a(a,"facebook-share",{width:550,height:320})};var l5a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;z.p(Z$,z.Dr);
Z$.prototype.open=function(a,b){this.ua=a;this.zw=b;this.Ea=this.oE.open({bodyHtml:z.Uz(g4a,this.zw),type:"tweet"},!0);a=this.Ea.query(".js-tweetEditor-text");b=this.ra;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.oH=new z.YZ(b,a,c(d),!0);a=new z.RZ(140,!0);a.z9=Y$;this.oH.bb(a);a=k5a(c4a,this.zw,z.Cr);this.oH.rd(a);this.oH.focus();n5a(this);z.S(this.Ea.jc).aa("remove-textshot",this.zca.bind(this,!1),this).aa("add-textshot",this.zca.bind(this,!0),this).aa("toggle-expand-image",this.Lza,
this);this.Ea.subscribe("submit",this.yAa.bind(this))};Z$.prototype.yAa=function(){var a=this.oH.jb();if(o5a(this,a)){var b=this.jN?m5a(this):null;z.w(z.t(this.oa.post(this.la.ka(z.Kxa),{tweet:a,textshotInfo:b}),function(a){a=z.Wz(e4a,{id:a.value});a=z.Uz(i4a,{IHa:a});this.xa.qa(a,{type:"success",Qp:1E4})},this),function(a){z.QA(a);this.xa.qa(h4a(),"error")},this);z.jC(z.qAa,{postId:this.ua.id,type:this.zw.shareType,source:this.zw.XGa,dest:"twitter",style:this.jN?"textshot":null});this.Ea.close()}};
Z$.prototype.zca=function(a){this.jN=a;z.sd(this.Ea.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.sd(this.Ea.query(".js-tweetEditor-addTextshot"),"u-hide",a)};Z$.prototype.Lza=function(){var a=this.Ea.query(".js-tweetEditor-image");z.td(a,"tweetEditor-image--expanded")};z.f=p5a.prototype;z.f.WGa=function(a,b){var c=z.Ou(),d=a.creator||{},e=U3a(b),g=T3a(b),k=j5a(a,z.Cr);(b=t4a(b.d3()))&&z.Yd(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,zHa:e,yHa:g,shareType:"highlight",XGa:"highlight_menu"};z.w(z.t(this.ra.load("tweet-dialog"),function(b){b.open(a,l)}),z.QA);z.jC(z.gL,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.yC=function(a,b,c,d,e){var g=z.Ou().userId,k="highlight"==c?c4a:z.gsa,l=z.Cr,q=a.creator||{};b={content:b,name:q.name||"",username:q.username||"",twitterScreenName:q.twitterScreenName||"",cea:q.userId==g,url:j5a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):k5a(k,b,l);k=new z.Td("https://twitter.com/intent/tweet");z.de(k,"text",d);this.Sv(k);z.yB(z.gL,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.j6=function(a){var b=z.Cr,c=new z.al(z.Br(b)),c=(new z.Td(c.ka(z.gz,{catalogSlug:a.oe(),username:a.Ff().ik()}))).toString();a=z.B(""+z.ao(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.uI({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.Td("https://twitter.com/intent/tweet");z.de(b,"text",a);this.Sv(b)};
z.f.k6=function(a){var b=new z.al(z.Br(z.Cr)),b=(new z.Td(b.ka(z.Yy,{sequenceSlug:a.pd()}))).toString();a=z.B(""+z.ao(String(a.title))+" "+(""+b));b=new z.Td("https://twitter.com/intent/tweet");z.de(b,"text",a);this.Sv(b)};z.f.Sv=function(a){h5a(a,"twitter-share",{width:670,height:420})};z.m($$,z.ZZ);$$.prototype.ma=function(){var a=this;z.t(q5a(this),function(){z.ZZ.prototype.ma.call(this);a.toggle();z.S(a.na()).aa("homepage-link-clicked",a.jra,a)})};$$.prototype.toggle=function(){this.$l&&z.yB(z.bCa,{postId:this.kb});z.ZZ.prototype.toggle.call(this)};$$.prototype.jra=function(){z.yB(z.aCa,{postId:this.kb});this.Ia.navigate(this.la.ka(z.uy))};var r5a=z.TB,s5a=r5a.Ba();z.WB(s5a.scope("screen").add("quotes",x4a).add("quote-responses",g5a).add("responses-stream-control",W$).add("notes-data",D$),"WelcomeDrawer",$$);z.WB(s5a.scope("app"),"PlacementsControl",H$).add("twitter",p5a).add("facebook",i5a).add("tweet-dialog",Z$);z.cQ(r5a,"notes");}).call(this, _mdm);
